In [1]:
import numpy as np

Now with a kernel

In [2]:
def kernel(x, alpha=.1, rho=.1):
    return np.matrix(np.round(alpha**2 * np.exp(-x**2/(2*rho**2)),2))

In [3]:
npts = 5
xn = np.arange(5)
x = np.subtract.outer(xn, xn)
Kx = kernel(x, alpha=.1, rho=2.)
Kz = kernel(x, alpha=.1, rho=1.5)

In [4]:
print(x)
print('\n')
print(Kx)
print('\n')
print(Kz)

[[ 0 -1 -2 -3 -4]
 [ 1  0 -1 -2 -3]
 [ 2  1  0 -1 -2]
 [ 3  2  1  0 -1]
 [ 4  3  2  1  0]]


[[0.01 0.01 0.01 0.   0.  ]
 [0.01 0.01 0.01 0.01 0.  ]
 [0.01 0.01 0.01 0.01 0.01]
 [0.   0.01 0.01 0.01 0.01]
 [0.   0.   0.01 0.01 0.01]]


[[0.01 0.01 0.   0.   0.  ]
 [0.01 0.01 0.01 0.   0.  ]
 [0.   0.01 0.01 0.01 0.  ]
 [0.   0.   0.01 0.01 0.01]
 [0.   0.   0.   0.01 0.01]]


In [5]:
print(Kx * Kz)

[[0.0002 0.0003 0.0002 0.0001 0.    ]
 [0.0002 0.0003 0.0003 0.0002 0.0001]
 [0.0002 0.0003 0.0003 0.0003 0.0002]
 [0.0001 0.0002 0.0003 0.0003 0.0002]
 [0.     0.0001 0.0002 0.0003 0.0002]]


In [6]:
print(np.dot(Kx, Kz))

[[0.0002 0.0003 0.0002 0.0001 0.    ]
 [0.0002 0.0003 0.0003 0.0002 0.0001]
 [0.0002 0.0003 0.0003 0.0003 0.0002]
 [0.0001 0.0002 0.0003 0.0003 0.0002]
 [0.     0.0001 0.0002 0.0003 0.0002]]


Now lets build a proper multiplied kernel

In [7]:
def kprod(x, y, ax, lx, ay, ly):
    kx = ax**2 * np.exp(-np.subtract.outer(x,x)**2 / (2*lx**2))
    ky = ay**2 * np.exp(-np.subtract.outer(y,y)**2 / (2*ly**2))
    return np.matrix(np.round(kx * ky,2))

In [8]:
xn = np.arange(5)
x = np.subtract.outer(xn, xn)
Kprod = kprod(xn, xn, 1., 10., 4., 10.)

In [9]:
Kprod

matrix([[16.  , 15.84, 15.37, 14.62, 13.63],
        [15.84, 16.  , 15.84, 15.37, 14.62],
        [15.37, 15.84, 16.  , 15.84, 15.37],
        [14.62, 15.37, 15.84, 16.  , 15.84],
        [13.63, 14.62, 15.37, 15.84, 16.  ]])

In [10]:
Kx = kernel(x, 1., 10.)
Ky = kernel(x, 4., 10.)

In [11]:
np.dot(Kx, Ky)

matrix([[75.5628, 76.6504, 76.9888, 76.588 , 75.4396],
        [76.7732, 77.8944, 78.2544, 77.8632, 76.7116],
        [77.0546, 78.1956, 78.5728, 78.1956, 77.0546],
        [76.7116, 77.8632, 78.2544, 77.8944, 76.7732],
        [75.4396, 76.588 , 76.9888, 76.6504, 75.5628]])

In [12]:
np.exp(np.log(Kx) + np.log(Ky))

matrix([[16.    , 15.92  , 15.3664, 14.688 , 13.5884],
        [15.92  , 16.    , 15.92  , 15.3664, 14.688 ],
        [15.3664, 15.92  , 16.    , 15.92  , 15.3664],
        [14.688 , 15.3664, 15.92  , 16.    , 15.92  ],
        [13.5884, 14.688 , 15.3664, 15.92  , 16.    ]])